<h3>CUSTOMER DETAILS</h3>
<div style="line-height: 0.5; font-size : 14px">
	<p>Name : {{ $customer->companyname }}</p>
	<p>Address : {{ $customer->companyaddress }}</p>
	<p>Nature of business : {{ $customer->companynature }}</p>
	<p>Owner nationality : {{ $customer->ownernationality }}</p>
	@if($approver == "om")
		<p>You can approve this customer on <a href="https://odash.minamotocorpsystems.com">https://odash.minamotocorpsystems.com</a></p>
	@else
		<p>You can approve this customer on <a href="https://gdash.minamotocorpsystems.com">https://gdash.minamotocorpsystems.com</a></p>
	@endif
</div>
<h5>This email is auto generated by the system.</h5>