<h3>PURCHASE ORDER DETAILS</h3>
<div style="font-size : 14px">
	<p>Supplier : {{ $poDetails->supplier }}</p>
	<p>Purchase order no. : {{ $poDetails->poNumber }}</p>
	<p>Purchase order date : {{ $poDetails->date  }}</p>
	<p>Purchase request number/s : {{ $poDetails->prNumbers }}</p>
	<p>Requested by : {{ $poDetails->requestee }}</p>
	<p>You can approve this request on <a href="https://gdash.minamotocorpsystems.com">https://gdash.minamotocorpsystems.com</a></p>
</div>
<table 
	style="font-size : 12px; padding : 0; margin : 0; width: 100%"
	border="1"
	cellspacing="0" 
	cellpadding="3"
	>
	<thead>
		<tr style="background : #3c8dbc; color : #ffffff; text-align: center;">
			<th>Code</th>
			<th>Material Specification</th>
			<th>Quantity</th>
			<th>Unit</th>
			<th>Unit price</th>
			<th>Amount</th>
			<th>Delivery date</th>
		</tr>
	</thead>
	<tbody style="text-align: center;">
		@foreach($poDetails->items as $item)
		<tr>
			<td>{{ $item->spoi_code }}</td>
			<td>{{ $item->spoi_mspecs }}</td>
			<td>{{ $item->spoi_quantity }}</td>
			<td>{{ $item->spoi_uom }}</td>
			<td>{{ $item->spoi_unitprice }}</td>
			<td>{{ number_format($item->spoi_unitprice * $item->spoi_quantity, 2)  }}</td>
			<td>{{ $item->spoi_deliverydate }}</td>
		</tr>
		@endforeach
	</tbody>
</table>
<h5>This email is auto generated by the system.</h5>